routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');

// Manufacturers Route
Route::group(['prefix' => 'manufacturers'], function() {
    Route::get('/', 'ManufacturerController@index');
    Route::get('/add', 'ManufacturerController@add');
    Route::post('/store', 'ManufacturerController@store')->name('manufacturers.store');
    Route::get('/{id}/edit', 'ManufacturerController@edit')->name('manufacturers.edit');
    Route::post('/{id}/update', 'ManufacturerController@update')->name('manufacturers.update');
    Route::get('/{id}/delete', 'ManufacturerController@delete')->name('manufacturers.delete');
});


// Customers Route
Route::group(['prefix' => 'customers'], function() {
Route::get('/', 'CustomerController@index');
Route::get('/add', 'CustomerController@add');
Route::post('/store', 'CustomerController@store')->name('customers.store');
Route::get('/{id}/edit', 'CustomerController@edit')->name('customers.edit');
Route::post('/{id}/update', 'CustomerController@update')->name('customers.update');
Route::get('/{id}/delete', 'CustomerController@delete')->name('customers.delete');
});

// Medicine Route
Route::group(['prefix' => 'medicine'], function() {
Route::get('/', 'MedicineController@index');
Route::get('/add', 'MedicineController@add');
Route::post('/store', 'MedicineController@store')->name('medicine.store');
Route::get('/{id}/edit', 'MedicineController@edit')->name('medicine.edit');
Route::post('/{id}/update', 'MedicineController@update')->name('medicine.update');
Route::get('/{id}/delete', 'MedicineController@delete')->name('medicine.delete');
// Medicine Category Route
Route::get('/category', 'MedicineController@medicine_cat');
Route::post('/cat_store', 'MedicineController@cat_store')->name('medicine.cat_store');
Route::get('/{id}/cat_edit', 'MedicineController@cat_edit')->name('medicine.cat_edit');
Route::post('/{id}/cat_update', 'MedicineController@cat_update')->name('medicine.cat_update');
Route::get('/{id}/cat_delete', 'MedicineController@cat_delete')->name('medicine.cat_delete');
// Medicine Type Route
Route::get('/type', 'MedicineController@medicine_type');
Route::post('/type_store', 'MedicineController@type_store')->name('medicine.type_store');
Route::get('/{id}/type_edit', 'MedicineController@type_edit')->name('medicine.type_edit');
Route::post('/{id}/type_update', 'MedicineController@type_update')->name('medicine.type_update');
Route::get('/{id}/type_delete', 'MedicineController@type_delete')->name('medicine.type_delete');
// Medicine Unit Route
Route::get('/unit', 'MedicineController@medicine_unit');
Route::post('/unit_store', 'MedicineController@unit_store')->name('medicine.unit_store');
Route::get('/{id}/unit_edit', 'MedicineController@unit_edit')->name('medicine.unit_edit');
Route::post('/{id}/unit_update', 'MedicineController@unit_update')->name('medicine.unit_update');
Route::get('/{id}/unit_delete', 'MedicineController@unit_delete')->name('medicine.unit_delete');
});

// Bank Route
Route::group(['prefix' => 'bank'], function() {
    Route::get('/', 'BankController@index');
    Route::get('/add', 'BankController@add');
    Route::post('/store', 'BankController@store')->name('bank.store');
    Route::get('/{id}/edit', 'BankController@edit')->name('bank.edit');
    Route::post('/{id}/update', 'BankController@update')->name('bank.update');
    Route::get('/{id}/delete', 'BankController@delete')->name('bank.delete');
});


//company  route
Route::group(['prefix' => '/'], function() {
     Route::resource('company', 'CompanyController');
   
});



// Supplier Route
Route::group(['prefix' => 'supplier'], function() {
    Route::get('/', 'SupplierController@index');
    Route::get('/add', 'SupplierController@add');
    Route::post('/store', 'SupplierController@store')->name('supplier.store');
    Route::get('/{id}/edit', 'SupplierController@edit')->name('supplier.edit');
    Route::post('/{id}/update', 'SupplierController@update')->name('supplier.update');
    Route::get('/{id}/delete', 'SupplierController@delete')->name('supplier.delete');
});

// Purchase Route
Route::group(['prefix' => 'purchase'], function() {
    Route::get('/', 'PurchaseController@index');
    Route::get('/add', 'PurchaseController@add');
    Route::post('/store', 'PurchaseController@store')->name('purchase.store');
    Route::get('/{id}/show', 'PurchaseController@show')->name('purchase.show');
    Route::get('/{id}/delete', 'PurchaseController@delete')->name('purchase.delete');
    Route::get('/search','PurchaseController@search')->name('purchase.search');
  //  Route::get('/{id}/edit', 'PurchaseController@edit')->name('purchase.edit');
 //   Route::post('/{id}/update', 'PurchaseController@update')->name('purchase.update');
 //   Route::get('/{id}/delete', 'PurchaseController@delete')->name('purchase.delete');
    });
    Route::get('/addajax','PurchaseController@addajax');
    Route::get('/addPrice','PurchaseController@addprice');


Route::group(['prefix' => 'stock'], function() {
    Route::get('/', 'StockController@quantity');

    });


Route::group(['prefix' => '/'], function() {
     Route::resource('/account', 'AccountController');
     Route::get('/expadd','AccountController@expadd')->name('account.expadd');
     Route::get('/expcreate','AccountController@exp_create')->name('account.exp_create');
     Route::get('/explist','AccountController@exp_list')->name('account.explist');
     Route::get('/{id}/expense_delete','AccountController@d')->name('account.d');
     Route::get('/income','AccountController@income')->name('total.income');
   
});


Route::group(['prefix' => '/due'], function() {

     Route::get('/CustomerDue','DueController@customer')->name('due.customer');
     Route::get('/{id}/CusDueShow','DueController@show')->name('due.show');
     Route::get('/amount/store','DueController@store')->name('amount.store');
     Route::get('/{id}/amount/total','DueController@total')->name('amount.total');

     Route::get('/ManufacturerDue','DueController@manufacturer')->name('due.manufacturer');
     Route::get('/{id}/ManuDueShow','DueController@manuShow')->name('manu.show');
     Route::get('manu/amount/store','DueController@manustore')->name('manu.store');
     Route::get('/{id}/manufacturer/total','DueController@manutotal')->name('manu.total');

});


// Sales Route
Route::group(['prefix' => 'sales'], function() {
    Route::get('/', 'SalesController@index');
    Route::get('/add', 'SalesController@add');
    Route::post('/store', 'SalesController@store')->name('sales.store');
    Route::get('/{id}/delete', 'SalesController@delete')->name('sale.delete');
    Route::get('/{id}/show', 'SalesController@show')->name('sale.show');
    Route::get('/search', 'SalesController@search')->name('sale.search');
});
Route::get('/batchID','SalesController@batchID');
Route::get('/expired','SalesController@expired');
Route::get('/unitPrice','SalesController@unitPrice');

resources/views/cominfo/add.blade.php
@extends('master')


@section('content')
    <!-- Main content -->
    <section class="content">
          
            <!-- general form elements -->
            <div class="box box-primary">
              <div class="box-header">
                <h2 class="box-title">Add Supplier</h2>
              </div>
              <!-- /.card-header -->

                @if ($errors->any())
                    <div class="alert alert-warning alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        @if ($errors->count() == 1)
                            {{$errors->first()}}
                        @else
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif
                    </div>
            @endif
              <!-- form start -->
               <form role="form" action="{{route('company.store')}}" enctype="multipart/form-data" method="POST">
                  {{csrf_field()}}
                <div class="box-body">
                  <div class="form-group">
                     <div class="row">
                     <div class="col-md-3">
                    <label for="sup_name">{{ __('Company Name *') }}</label>
                 </div>
                    <div class="col-md-8">
                    <input type="text" class="form-control" value="{{old('cname')}}" id="cname" name="cname" placeholder="Enter Company Name">
                 </div>
              </div>
                  </div>
                   <div class="form-group">
                     <div class="row">
                     <div class="col-md-3">
                    <label for="sup_name">{{ __('Company Tag Line *') }}</label>
                 </div>
                    <div class="col-md-8">
                    <input type="text" class="form-control" value="{{old('tag')}}" id="tag" name="tag" placeholder="Enter Company Tag Line">
                 </div>
              </div>
                  </div>
                  <div class="form-group">
                     <div class="row">
                     <div class="col-md-3">
                    <label for="sup_phone">{{ __('phone *') }}</label>
                 </div>
                 <div class="col-md-8">
                    <input type="tel" class="form-control" value="{{old('phone')}}" id="phone" name="phone" placeholder="Enter Company 1st Mobile Number" pattern="[0-9]{11}">
                 </div>
              </div>
                  </div>
                   <div class="form-group">
                     <div class="row">
                     <div class="col-md-3">
                    <label for="sup_phone">{{ __('Company Mobile 2nd ') }}</label>
                 </div>
                 <div class="col-md-8">
                    <input type="tel" class="form-control" value="{{old('phone2')}}" id="phone2" name="phone2" placeholder="Company 2nd Mobile Number" pattern="[0-9]{11}">
                 </div>
              </div>
                  </div>
                   <div class="form-group">
                     <div class="row">
                     <div class="col-md-3">
                    <label for="sup_address">{{ __('Company Email 1st *') }}</label>
                 </div>
                 <div class="col-md-8">
                    <input type="text" class="form-control" id="sel1" value="{{old('email1')}}" placeholder="Enter 1st email" id="email1" name="email1">
                 </div>
              </div>
                  </div>
                    <div class="form-group">
                     <div class="row">
                     <div class="col-md-3">
                    <label for="sup_address">{{ __('Company Email 2nd') }}</label>
                 </div>
                 <div class="col-md-8">
                     <input type="text" class="form-control" id="email2" value="{{old('email2')}}" placeholder="Enter 2nd email" name="email2">
                 </div>
                 </div>
              </div>
               

                   <div class="form-group">
                     <div class="row">
                     <div class="col-md-3">
                    <label for="customer_address">{{ __('Customer Address') }}</label>
                 </div>
                 <div class="col-md-8">
                    <textarea class="form-control" name="address" rows="3" value="{{old('address')}}"  placeholder="Enter Company Address">{{old('customer_address')}}</textarea>
                 </div>
              </div>
                  </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-3">
                                <label for="sup_details">{{ __('Logo') }}</label>
                            </div>
                            <div class="col-md-8">
                                <input type="file"  id="usr" rows="3" value="{{old('logo')}}" placeholder="Company Logo" name="logo">
                            </div>
                        </div>
                    </div>
                 
                  </div>

                <div class="box-footer">
                  <div class="col-md-offset-3">
                  <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
                      <input class="btn btn-warning" type="reset" value="{{ __('Reset') }}">
               </div>
               </div>
              </form>
            </div>
            <!-- /.card -->

    </section>
 @endsection

resources/views/cominfo/edit.blade.php
@extends('master')


@section('content')
    <!-- Main content -->
    <section class="content">
          
            <!-- general form elements -->
            <div class="box box-primary">
              <div class="box-header">
                <h2 class="box-title">Add Supplier</h2>
              </div>
              <!-- /.card-header -->

                @if ($errors->any())
                    <div class="alert alert-warning alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        @if ($errors->count() == 1)
                            {{$errors->first()}}
                        @else
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif
                    </div>
            @endif
              <!-- form start -->
               <form role="form" action="{{route('company.update',[$company->id])}}" method="post" enctype="multipart/form-data" >
                  {{csrf_field()}}
                  @method('put')
                <div class="box-body">
                  <div class="form-group">
                     <div class="row">
                     <div class="col-md-3">
                    <label for="sup_name">{{ __('Company Name *') }}</label>
                 </div>
                    <div class="col-md-8">
                    <input type="text" class="form-control" value="{{$company->cname}}" id="cname" name="cname" placeholder="Enter Company Name">
                 </div>
              </div>
                  </div>
                   <div class="form-group">
                     <div class="row">
                     <div class="col-md-3">
                    <label for="sup_name">{{ __('Company Tag Line *') }}</label>
                 </div>
                    <div class="col-md-8">
                    <input type="text" class="form-control" value="{{$company->tag}}" id="tag" name="tag" placeholder="Enter Company Tag Line">
                 </div>
              </div>
                  </div>
                  <div class="form-group">
                     <div class="row">
                     <div class="col-md-3">
                    <label for="sup_phone">{{ __('phone *') }}</label>
                 </div>
                 <div class="col-md-8">
                    <input type="tel" class="form-control" value="{{$company->phone}}" id="phone" name="phone" placeholder="Enter Company 1st Mobile Number" pattern="[0-9]{11}">
                 </div>
              </div>
                  </div>
                   <div class="form-group">
                     <div class="row">
                     <div class="col-md-3">
                    <label for="sup_phone">{{ __('Company Mobile 2nd ') }}</label>
                 </div>
                 <div class="col-md-8">
                    <input type="tel" class="form-control" value="{{$company->phone2}}" id="phone2" name="phone2" placeholder="Company 2nd Mobile Number" pattern="[0-9]{11}">
                 </div>
              </div>
                  </div>
                   <div class="form-group">
                     <div class="row">
                     <div class="col-md-3">
                    <label for="sup_address">{{ __('Company Email 1st *') }}</label>
                 </div>
                 <div class="col-md-8">
                    <input type="text" class="form-control" id="sel1" value="{{$company->email1}}" placeholder="Enter 1st email" id="email1" name="email1">
                 </div>
              </div>
                  </div>
                    <div class="form-group">
                     <div class="row">
                     <div class="col-md-3">
                    <label for="sup_address">{{ __('Company Email 2nd') }}</label>
                 </div>
                 <div class="col-md-8">
                     <input type="text" class="form-control" id="email2" value="{{$company->email2}}" placeholder="Enter 2nd email" name="email2">
                 </div>
                 </div>
              </div>
                  
                  <div class="form-group">
                     <div class="row">
                     <div class="col-md-3">
                    <label for="sup_address">{{ __('Company Address') }}</label>
                 </div>
                 <div class="col-md-8">
                    <textarea class="form-control"  rows="3" placeholder="Company Address" value="{{$company->address}}" name="address">{{$company->address}}</textarea>
                 </div>
              </div>
                  </div>
                 <!--    <div class="form-group">
                        <div class="row">
                            <div class="col-md-3">
                                <label for="sup_details">{{ __('Logo') }}</label>
                            </div>
                            <div class="col-md-2">
                                            @if ("{{ $company->logo }}")
                                                <img src="{{ asset('uploads/bank/'.$company->logo) }}" width="70">
                                            @else
                                                <p>No image found</p>
                                            @endif
                                        </div>
                        </div>
                    </div> -->
                      <div class="form-group">
                            <div class="row">
                                <div class="col-md-3">
                                    <label for="logo">{{ __('Signature') }}</label>
                                </div>
                                <div class="col-md-8">
                                    <div class="row">
                                        <div class="col-md-2">
                                            @if ("{{ $company->logo }}")
                                                <img src="{{ asset('uploads/company/'.$company->logo) }}" width="50">
                                            @else
                                                <p>No image found</p>
                                            @endif
                                        </div>
                                        <div class="col-md-10">
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file" value="{{$company->logo}}" name="logo" class="custom-file-input" id="logo">
                                                    <p class="help-block">Change Bank Signature as Images</p>
                                                </div>
                                                <!--     <div class="input-group-append">
                                                         <span class="input-group-text" id="">Upload</span>
                                                     </div>-->
                                            </div>
                                        </div>
                                    </div>


                                </div>
                            </div>
                        </div>

                 
                  </div>

                <div class="box-footer">
                  <div class="col-md-offset-3">
                  <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
                      <input class="btn btn-warning" type="reset" value="{{ __('Reset') }}">
               </div>
               </div>
              </form>
            </div>
            <!-- /.card -->

    </section>
 @endsection

resources/views/cominfo/index.blade.php
@extends('master')

@section('content')
   <!-- Main content -->
   <section class="content">
      <div class="row">
         <div class="col-xs-12">
            <div class="box">
               <div class="box-header">
                  <h3 class="box-title">All Supplier List</h3>
                  <a href="{{url('/company/create')}}" class="btn btn-primary pull-right">Add Information</a>
               </div>
               <!-- /.box-header -->
               <div class="box-body">
                  <table id="baseIT" class="table table-bordered table-striped">
                     <thead>
                     <tr>
                        <th>SL.</th>
                        <th>Company Name</th>
                        <th>Tag</th>
                        <th>Mobile 1</th>
                        <th>Mobile 2</th>
                        <th>Email 1</th>
                        <th>Email 2</th>
                        <th>Address</th>
                        <th>Logo</th>
                        <th>Action</th>

                     </tr>
                     </thead>
                     <tbody>
                     @foreach($company as $comp)
                         <tr>
                           <td>{{ $no++ }}</td>
                           <td>{{$comp->cname}}</td>
                           <td>{{$comp->tag}}</td>
                           <td>{{$comp->phone}}</td>
                           <td>{{$comp->phone2}}</td>
                           <td>{{$comp->email1}}</td>
                           <td>{{$comp->email2}}</td>
                           <td>{{$comp->address}}</td>
                           <td><img src="{{ asset('uploads/company/'.$comp->logo) }}" width="80"></td>
                           <td>
                              <a href="{{route('company.edit',[$comp->id])}}"><button class="btn btn-warning"><i class="fa fa-pencil-square-o"></i></button></a>

                             <!--  <a href="{{route('company.destroy',[$comp->id])}}"><button class="btn btn-danger" onClick="return confirm('Are you sure you want toDestroy this data permanently?')"><i class="fa fa-trash-o"></i></button></a> -->

                              <form id="delete-form-{{ $comp->id }}" action="{{ route('company.destroy',$comp->id) }}" style="display: none;" method="POST">
                           {{csrf_field()}}company
                           {{ method_field('DELETE') }}
                       </form>
                       <button type="button" class="btn btn-danger" title="Delete" onclick="if(confirm('Are you sure? You want to delete this?')){
                           event.preventDefault();
                           document.getElementById('delete-form-{{ $comp->id }}').submit();
                       }else {
                           event.preventDefault();
                               }"><i class="fa fa-trash-o"></i>
                       </button> 

                            

                           </td>
                        </tr>
                     @endforeach
                     </tbody>
                     <tfoot>
                     <tr>
                       <th>SL.</th>
                        <th>Company Name</th>
                        <th>Tag</th>
                        <th>Mobile 1</th>
                        <th>Mobile 2</th>
                        <th>Email 1</th>
                        <th>Email 2</th>
                        <th>Address</th>
                        <th>Logo</th>
                        <th>Action</th>
                     </tr>
                     </tfoot>
                  </table>
               </div>
               <!-- /.box-body -->
            </div>
            <!-- /.box -->
         </div>
         <!-- /.col -->
      </div>
      <!-- /.row -->
   </section>
   <!-- /.content -->
@endsection