routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');

// Manufacturers Route
Route::group(['prefix' => 'manufacturers'], function() {
    Route::get('/', 'ManufacturerController@index');
    Route::get('/add', 'ManufacturerController@add');
    Route::post('/store', 'ManufacturerController@store')->name('manufacturers.store');
    Route::get('/{id}/edit', 'ManufacturerController@edit')->name('manufacturers.edit');
    Route::post('/{id}/update', 'ManufacturerController@update')->name('manufacturers.update');
    Route::get('/{id}/delete', 'ManufacturerController@delete')->name('manufacturers.delete');
});


// Customers Route
Route::group(['prefix' => 'customers'], function() {
Route::get('/', 'CustomerController@index');
Route::get('/add', 'CustomerController@add');
Route::post('/store', 'CustomerController@store')->name('customers.store');
Route::get('/{id}/edit', 'CustomerController@edit')->name('customers.edit');
Route::post('/{id}/update', 'CustomerController@update')->name('customers.update');
Route::get('/{id}/delete', 'CustomerController@delete')->name('customers.delete');
});

// Medicine Route
Route::group(['prefix' => 'medicine'], function() {
Route::get('/', 'MedicineController@index');
Route::get('/add', 'MedicineController@add');
Route::post('/store', 'MedicineController@store')->name('medicine.store');
Route::get('/{id}/edit', 'MedicineController@edit')->name('medicine.edit');
Route::post('/{id}/update', 'MedicineController@update')->name('medicine.update');
Route::get('/{id}/delete', 'MedicineController@delete')->name('medicine.delete');
// Medicine Category Route
Route::get('/category', 'MedicineController@medicine_cat');
Route::post('/cat_store', 'MedicineController@cat_store')->name('medicine.cat_store');
Route::get('/{id}/cat_edit', 'MedicineController@cat_edit')->name('medicine.cat_edit');
Route::post('/{id}/cat_update', 'MedicineController@cat_update')->name('medicine.cat_update');
Route::get('/{id}/cat_delete', 'MedicineController@cat_delete')->name('medicine.cat_delete');
// Medicine Type Route
Route::get('/type', 'MedicineController@medicine_type');
Route::post('/type_store', 'MedicineController@type_store')->name('medicine.type_store');
Route::get('/{id}/type_edit', 'MedicineController@type_edit')->name('medicine.type_edit');
Route::post('/{id}/type_update', 'MedicineController@type_update')->name('medicine.type_update');
Route::get('/{id}/type_delete', 'MedicineController@type_delete')->name('medicine.type_delete');
// Medicine Unit Route
Route::get('/unit', 'MedicineController@medicine_unit');
Route::post('/unit_store', 'MedicineController@unit_store')->name('medicine.unit_store');
Route::get('/{id}/unit_edit', 'MedicineController@unit_edit')->name('medicine.unit_edit');
Route::post('/{id}/unit_update', 'MedicineController@unit_update')->name('medicine.unit_update');
Route::get('/{id}/unit_delete', 'MedicineController@unit_delete')->name('medicine.unit_delete');
});

// Bank Route
Route::group(['prefix' => 'bank'], function() {
    Route::get('/', 'BankController@index');
    Route::get('/add', 'BankController@add');
    Route::post('/store', 'BankController@store')->name('bank.store');
    Route::get('/{id}/edit', 'BankController@edit')->name('bank.edit');
    Route::post('/{id}/update', 'BankController@update')->name('bank.update');
    Route::get('/{id}/delete', 'BankController@delete')->name('bank.delete');
});


//company  route
Route::group(['prefix' => '/'], function() {
     Route::resource('company', 'CompanyController');
   
});



// Supplier Route
Route::group(['prefix' => 'supplier'], function() {
    Route::get('/', 'SupplierController@index');
    Route::get('/add', 'SupplierController@add');
    Route::post('/store', 'SupplierController@store')->name('supplier.store');
    Route::get('/{id}/edit', 'SupplierController@edit')->name('supplier.edit');
    Route::post('/{id}/update', 'SupplierController@update')->name('supplier.update');
    Route::get('/{id}/delete', 'SupplierController@delete')->name('supplier.delete');
});

// Purchase Route
Route::group(['prefix' => 'purchase'], function() {
    Route::get('/', 'PurchaseController@index');
    Route::get('/add', 'PurchaseController@add');
    Route::post('/store', 'PurchaseController@store')->name('purchase.store');
    Route::get('/{id}/show', 'PurchaseController@show')->name('purchase.show');
    Route::get('/{id}/delete', 'PurchaseController@delete')->name('purchase.delete');
    Route::get('/search','PurchaseController@search')->name('purchase.search');
  //  Route::get('/{id}/edit', 'PurchaseController@edit')->name('purchase.edit');
 //   Route::post('/{id}/update', 'PurchaseController@update')->name('purchase.update');
 //   Route::get('/{id}/delete', 'PurchaseController@delete')->name('purchase.delete');
    });
    Route::get('/addajax','PurchaseController@addajax');
    Route::get('/addPrice','PurchaseController@addprice');


Route::group(['prefix' => 'stock'], function() {
    Route::get('/', 'StockController@quantity');

    });


Route::group(['prefix' => '/'], function() {
     Route::resource('/account', 'AccountController');
     Route::get('/expadd','AccountController@expadd')->name('account.expadd');
     Route::get('/expcreate','AccountController@exp_create')->name('account.exp_create');
     Route::get('/explist','AccountController@exp_list')->name('account.explist');
     Route::get('/{id}/expense_delete','AccountController@d')->name('account.d');
     Route::get('/income','AccountController@income')->name('total.income');
   
});


Route::group(['prefix' => '/due'], function() {

     Route::get('/CustomerDue','DueController@customer')->name('due.customer');
     Route::get('/{id}/CusDueShow','DueController@show')->name('due.show');
     Route::get('/amount/store','DueController@store')->name('amount.store');
     Route::get('/{id}/amount/total','DueController@total')->name('amount.total');

     Route::get('/ManufacturerDue','DueController@manufacturer')->name('due.manufacturer');
     Route::get('/{id}/ManuDueShow','DueController@manuShow')->name('manu.show');
     Route::get('manu/amount/store','DueController@manustore')->name('manu.store');
     Route::get('/{id}/manufacturer/total','DueController@manutotal')->name('manu.total');

});


// Sales Route
Route::group(['prefix' => 'sales'], function() {
    Route::get('/', 'SalesController@index');
    Route::get('/add', 'SalesController@add');
    Route::post('/store', 'SalesController@store')->name('sales.store');
    Route::get('/{id}/delete', 'SalesController@delete')->name('sale.delete');
    Route::get('/{id}/show', 'SalesController@show')->name('sale.show');
    Route::get('/search', 'SalesController@search')->name('sale.search');
});
Route::get('/batchID','SalesController@batchID');
Route::get('/expired','SalesController@expired');
Route::get('/unitPrice','SalesController@unitPrice');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
        <!--        <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>-->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/apps.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    
<!-- Mirrored from thememinister.com/crm/register.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 20 Oct 2019 06:53:05 GMT -->
<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

  		<title>{{ config('app.name', 'Laravel') }}</title>
        <!-- Favicon and touch icons -->
        <link rel="shortcut icon" href="{{asset('assets/dist/img/ico/favicon.png')}}" type="image/x-icon">
        <!-- Bootstrap -->
        <link href="{{asset('assets/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
        
        <!-- Bootstrap rtl -->
        <!--<link href="assets/bootstrap-rtl/bootstrap-rtl.min.css" rel="stylesheet" type="text/css"/>-->
         <!-- Pe-icon-7-stroke -->
        <link href="{{asset('assets/pe-icon-7-stroke/css/pe-icon-7-stroke.css')}}" rel="stylesheet" type="text/css"/>
        <!-- style css -->
        <link href="{{asset('assets/dist/css/stylecrm.css')}}" rel="stylesheet" type="text/css"/>
        <!-- Theme style rtl -->
        <!--<link href="assets/dist/css/stylecrm-rtl.css" rel="stylesheet" type="text/css"/>-->

         

    </head>
    <body>
    	<div class="login-wrapper" style="background-image: url('dist/img/m.jpg');background-size: cover; padding-bottom: 42px;">
     <!--  <div class="back-link">
                <a href="{{ url('/') }}" class="btn btn-add">{{ config('app.name', 'Laravel') }}</a>
            </div>-->

        @yield('content')
    </div>
    <script src="{{asset('assets/plugins/jQuery/jquery-1.12.4.min.js')}}" type="text/javascript"></script>
        <!-- bootstrap js -->
        <script src="{{asset('assets/bootstrap/js/bootstrap.min.js')}}" type="text/javascript"></script>
</body>
</html>

resources/views/layouts/footer.blade.php
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1.0
    </div>
    <strong>Copyright &copy; 2019 <a href="https://baseit.com.bd">BASE IT</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  
<!-- footer er extra line gula -->

  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->


  <!-- Bootstrap 3.3.7 -->
  <script src="{{asset('bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
  <!-- DataTables -->
  <script src="{{asset('bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
  <!-- Select2 -->
  <script src="{{asset('bower_components/select2/dist/js/select2.full.min.js')}}"></script>
  <!-- bootstrap datepicker -->
  <script src="{{asset('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}"></script>
  <!-- FastClick -->
  <script src="{{asset('bower_components/fastclick/lib/fastclick.js')}}"></script>
  <!-- AdminLTE App -->
  <script src="{{asset('dist/js/adminlte.min.js')}}"></script>
  <!-- Sparkline -->
  <script src="{{asset('bower_components/jquery-sparkline/dist/jquery.sparkline.min.js')}}"></script>
  <!-- jvectormap  -->
  <script src="{{asset('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')}}"></script>
  <script src="{{asset('plugins/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script>
  <!-- SlimScroll -->
  <script src="{{asset('bower_components/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
  <!-- iCheck 1.0.1 -->
  <script src="{{asset('plugins/iCheck/icheck.min.js')}}"></script>
  <!-- ChartJS -->
  <script src="{{asset('bower_components/chart.js/Chart.js')}}"></script>
  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
  <script src="{{asset('dist/js/pages/dashboard2.js')}}"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="{{asset('dist/js/demo.js')}}"></script>

   <script src="https://cdn.datatables.net/buttons/1.6.0/js/dataTables.buttons.min.js"></script>
   <script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.flash.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
   <script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.html5.min.js"></script>
   <script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.print.min.js"></script>





   <script>
     $(function () {
       $("#baseIT").DataTable(
               {
                 dom: 'Bfrtip',
                 buttons: [
                   'copy', 'csv', 'excel', 'pdf', 'print'
                 ]
               }
       );
     });
   </script>



  <script>
    $(function () {
      //Initialize Select2 Elements
      $('.select2').select2()

      //Date picker
      $('.datepicker').datepicker({
        autoclose: true,
        format: 'dd-mm-yyyy'
      })

      //iCheck for checkbox and radio inputs
      $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
        checkboxClass: 'icheckbox_minimal-blue',
        radioClass   : 'iradio_minimal-blue'
      })
      //Red color scheme for iCheck
      $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
        checkboxClass: 'icheckbox_minimal-red',
        radioClass   : 'iradio_minimal-red'
      })
      //Flat red color scheme for iCheck
      $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
        checkboxClass: 'icheckbox_flat-green',
        radioClass   : 'iradio_flat-green'
      })

    })
  </script>



  <script>
    function test() {
      if (document.getElementById('payment_type').value == '1') {
        document.getElementById('bankID').style.display = 'block';
      } else {
        document.getElementById('bankID').style.display = 'none';
      }
    }
  </script>


<script>
function printContent(el){
var restorepage = $('body').html();
var printcontent = $('#' + el).clone();
$('body').empty().html(printcontent);
window.print();
$('body').html(restorepage);
}
</script>
  </body>
  </html>

resources/views/layouts/head.blade.php
<!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ $title }} | {{ config('app.name', 'Pharmacy') }}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <link rel="shortcut icon" href="{{asset('dist/img/pharmacy-mini-logo.png')}}" type="image/x-icon">

    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> -->
<!-- invoice css -->
  <!--  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">-->
   <!-- <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>-->
  <!--  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>-->
   <!-- end -->
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{asset('bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('bower_components/font-awesome/css/font-awesome.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{asset('bower_components/Ionicons/css/ionicons.min.css')}}">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="{{asset('plugins/iCheck/all.css')}}">
    <!-- bootstrap datepicker -->
    <link rel="stylesheet" href="{{asset('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{asset('bower_components/jvectormap/jquery-jvectormap.css')}}">
    <!-- DataTables -->
    <link rel="stylesheet" href="{{asset('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{{asset('bower_components/select2/dist/css/select2.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('dist/css/AdminLTE.min.css')}}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{asset('dist/css/skins/_all-skins.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/style.css')}}">




    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery 3 -->


    <script src="{{asset('bower_components/jquery/dist/jquery.min.js')}}"></script>

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  </head>
  <body class="hold-transition skin-green-light sidebar-mini">
  @if (session('status'))
    <div class="alert alert-success" role="alert">
      {{ session('status') }}
    </div>
  @endif
  <div class="wrapper">

resources/views/layouts/sidebar.blade.php
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar"  style="background-color: #2C3E50!important;">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{asset('dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ Auth::user()->name }}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li>
          <a href="{{url('/dashboard')}}">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
          </a>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-shopping-cart"></i> <span>Sales</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{url('/sales')}}"><i class="fa fa-circle-o"></i>All Sales</a></li>
            <li><a href="{{url('/sales/add')}}"><i class="fa fa-circle-o"></i>Add Sale</a></li>
            <li><a href="{{url('/due/CustomerDue')}}"><i class="fa fa-circle-o"></i>Customer Due</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-handshake-o"></i> <span>Customers</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{url('/customers')}}"><i class="fa fa-circle-o"></i>All Customers</a></li>
            <li><a href="{{url('/customers/add')}}"><i class="fa fa-circle-o"></i>Add Customer</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-medkit"></i> <span>Medicine</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{url('/medicine')}}"><i class="fa fa-circle-o"></i>All Medicine</a></li>
            <li><a href="{{url('/medicine/add')}}"><i class="fa fa-circle-o"></i>Add Medicine</a></li>
            <li><a href="{{url('/medicine/category')}}"><i class="fa fa-circle-o"></i>Medicine Category</a></li>
            <li><a href="{{url('/medicine/type')}}"><i class="fa fa-circle-o"></i>Medicine Type</a></li>
            <li><a href="{{url('/medicine/unit')}}"><i class="fa fa-circle-o"></i>Medicine Unit</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-building-o"></i> <span>Manufacturers</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{url('/manufacturers')}}"><i class="fa fa-circle-o"></i>All Manufacturers</a></li>
            <li><a href="{{url('/manufacturers/add')}}"><i class="fa fa-circle-o"></i>Add Manufacturer</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-shopping-basket"></i> <span>Purchase</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{url('/purchase')}}"><i class="fa fa-circle-o"></i>All Purchase</a></li>
            <li><a href="{{url('/purchase/add')}}"><i class="fa fa-circle-o"></i>Add Purchase</a></li>
            <li><a href="{{url('due/ManufacturerDue')}}"><i class="fa fa-circle-o"></i>Manufacturer Due</a></li>

          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-university"></i> <span>Bank</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{url('/bank')}}"><i class="fa fa-circle-o"></i>All Bank</a></li>
            <li><a href="{{url('/bank/add')}}"><i class="fa fa-circle-o"></i>Add Bank</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-user-plus"></i> <span>Supplier</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{url('/supplier')}}"><i class="fa fa-circle-o"></i>All Supplier</a></li>
            <li><a href="{{url('/supplier/add')}}"><i class="fa fa-circle-o"></i>Add Supplier</a></li>
          </ul>
        </li>
          <li class="treeview">
          <a href="#">
            <i class="fa fa-home"></i> <span>Company Information</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{route('company.index')}}"><i class="fa fa-circle-o"></i>Profile</a></li>
            <li><a href="{{route('company.create')}}"><i class="fa fa-circle-o"></i>Add Information</a></li>
          </ul>
        </li>

          <li>
          <a href="{{url('/stock')}}">
            <i class="fa fa-medkit"></i> <span>Stock</span>
          </a>
         </li>


         <li class="treeview">
          <a href="#">
            <i class="fa fa-shopping-basket"></i> <span>Account</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{url('/account/create')}}"><i class="fa fa-circle-o"></i>Expense Head</a></li>
            <li><a href="{{url('/expadd')}}"><i class="fa fa-circle-o"></i>Add Expense</a></li>
            <li><a href="{{url('explist')}}"><i class="fa fa-circle-o"></i>Expense List</a></li>
            <li><a href="{{url('/income')}}"><i class="fa fa-circle-o"></i>Income Statement</a></li>
          </ul>
        </li>


    
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>